version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    volumes: 
      - ./data:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nba
      LANG: C.UTF-8
    expose:
      - 3306
    networks:
      - mynetwork
  
  server:
    build: 
      context: .
      dockerfile: Dockerfile 
    environment:
      - PYTHONUNBUFFERED=1
    ports: 
      - 5000:5000
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
